/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface GlobalNodeInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addAdmin"
      | "allAdmins"
      | "batchAddAdmin"
      | "electDuration"
      | "electEndTime"
      | "electNode"
      | "electRewards"
      | "electStartTime"
      | "electStatus"
      | "electTox"
      | "elector"
      | "electorId"
      | "endElectorId"
      | "erc20Address"
      | "getElectReward"
      | "getElector"
      | "getElectorStatus"
      | "getEndElectorId"
      | "getVoteList"
      | "getVoteListLength"
      | "getVoteReward"
      | "getVoter"
      | "initialize"
      | "isAdmin"
      | "isElector"
      | "isWithdrawal"
      | "nodeTox"
      | "receiceTime"
      | "receiveElectReward"
      | "receiveVoteReward"
      | "removeAdmin"
      | "renounceAdmin"
      | "returnNodeToken"
      | "returnVote"
      | "returnVoteToken"
      | "rewards"
      | "setAboutAddress"
      | "setElectDuration"
      | "setSystemStatus"
      | "setVoteDuration"
      | "signerAddress"
      | "systemStatus"
      | "systemTox"
      | "totalElectEndTime"
      | "totalVoteTox"
      | "updateSystemElectorTox"
      | "vote"
      | "voteDuration"
      | "voteEndTime"
      | "voteList"
      | "voteStartTime"
      | "voteTotalCount"
      | "voteTox"
      | "voted"
      | "voter"
      | "voterId"
      | "withdrawalDuration"
      | "withdrawalNode"
      | "withdrawalNodeToken"
      | "withdrawalTime"
      | "withdrawalToken"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AdminAdded"
      | "AdminRemoved"
      | "ElectorDetail"
      | "ElectorWithdrawalToken"
      | "Initialized"
      | "Rewards"
      | "VoterDetail"
      | "VoterWithdrawalToken"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "addAdmin",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "allAdmins", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "batchAddAdmin",
    values: [AddressLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "electDuration",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "electEndTime",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "electNode",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "electRewards",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "electStartTime",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "electStatus",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "electTox",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "elector",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "electorId",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "endElectorId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "erc20Address",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getElectReward",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getElector",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getElectorStatus",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getEndElectorId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getVoteList",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getVoteListLength",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getVoteReward",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getVoter",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isAdmin",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isElector",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isWithdrawal",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "nodeTox",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "receiceTime",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "receiveElectReward",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "receiveVoteReward",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "removeAdmin",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceAdmin",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "returnNodeToken",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "returnVote",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "returnVoteToken",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "rewards",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setAboutAddress",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setElectDuration",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setSystemStatus",
    values: [AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setVoteDuration",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "signerAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "systemStatus",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "systemTox",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "totalElectEndTime",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "totalVoteTox",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updateSystemElectorTox",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "vote",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "voteDuration",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "voteEndTime",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "voteList",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "voteStartTime",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "voteTotalCount",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "voteTox",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "voted",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "voter",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "voterId",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawalDuration",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawalNode",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawalNodeToken",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawalTime",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawalToken",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "addAdmin", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "allAdmins", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "batchAddAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "electDuration",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "electEndTime",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "electNode", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "electRewards",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "electStartTime",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "electStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "electTox", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "elector", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "electorId", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "endElectorId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "erc20Address",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getElectReward",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getElector", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getElectorStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEndElectorId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getVoteList",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getVoteListLength",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getVoteReward",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getVoter", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isAdmin", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isElector", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isWithdrawal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "nodeTox", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "receiceTime",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "receiveElectReward",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "receiveVoteReward",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "returnNodeToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "returnVote", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "returnVoteToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "rewards", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setAboutAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setElectDuration",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setSystemStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setVoteDuration",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "signerAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "systemStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "systemTox", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalElectEndTime",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalVoteTox",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateSystemElectorTox",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "vote", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "voteDuration",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "voteEndTime",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "voteList", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "voteStartTime",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "voteTotalCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "voteTox", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "voted", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "voter", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "voterId", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "withdrawalDuration",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawalNode",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawalNodeToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawalTime",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawalToken",
    data: BytesLike
  ): Result;
}

export namespace AdminAddedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AdminRemovedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ElectorDetailEvent {
  export type InputTuple = [
    addr: AddressLike,
    eId: BigNumberish,
    amount: BigNumberish,
    isReturn: boolean
  ];
  export type OutputTuple = [
    addr: string,
    eId: bigint,
    amount: bigint,
    isReturn: boolean
  ];
  export interface OutputObject {
    addr: string;
    eId: bigint;
    amount: bigint;
    isReturn: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ElectorWithdrawalTokenEvent {
  export type InputTuple = [addr: AddressLike, amount: BigNumberish];
  export type OutputTuple = [addr: string, amount: bigint];
  export interface OutputObject {
    addr: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InitializedEvent {
  export type InputTuple = [version: BigNumberish];
  export type OutputTuple = [version: bigint];
  export interface OutputObject {
    version: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RewardsEvent {
  export type InputTuple = [
    addr: AddressLike,
    amount: BigNumberish,
    status: BigNumberish
  ];
  export type OutputTuple = [addr: string, amount: bigint, status: bigint];
  export interface OutputObject {
    addr: string;
    amount: bigint;
    status: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VoterDetailEvent {
  export type InputTuple = [
    addr: AddressLike,
    eId: BigNumberish,
    amount: BigNumberish,
    isReturn: boolean
  ];
  export type OutputTuple = [
    addr: string,
    eId: bigint,
    amount: bigint,
    isReturn: boolean
  ];
  export interface OutputObject {
    addr: string;
    eId: bigint;
    amount: bigint;
    isReturn: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VoterWithdrawalTokenEvent {
  export type InputTuple = [addr: AddressLike, amount: BigNumberish];
  export type OutputTuple = [addr: string, amount: bigint];
  export interface OutputObject {
    addr: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface GlobalNode extends BaseContract {
  connect(runner?: ContractRunner | null): GlobalNode;
  waitForDeployment(): Promise<this>;

  interface: GlobalNodeInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addAdmin: TypedContractMethod<[account: AddressLike], [void], "nonpayable">;

  allAdmins: TypedContractMethod<[], [string[]], "view">;

  batchAddAdmin: TypedContractMethod<
    [amounts: AddressLike[]],
    [void],
    "nonpayable"
  >;

  electDuration: TypedContractMethod<[], [bigint], "view">;

  electEndTime: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  electNode: TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;

  electRewards: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  electStartTime: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  electStatus: TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  electTox: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  elector: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  electorId: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  endElectorId: TypedContractMethod<[], [bigint], "view">;

  erc20Address: TypedContractMethod<[], [string], "view">;

  getElectReward: TypedContractMethod<[addr: AddressLike], [bigint], "view">;

  getElector: TypedContractMethod<
    [eId: BigNumberish],
    [[string, bigint, bigint, boolean, bigint]],
    "view"
  >;

  getElectorStatus: TypedContractMethod<[eId: BigNumberish], [boolean], "view">;

  getEndElectorId: TypedContractMethod<[], [bigint], "view">;

  getVoteList: TypedContractMethod<[addr: AddressLike], [bigint[]], "view">;

  getVoteListLength: TypedContractMethod<[addr: AddressLike], [bigint], "view">;

  getVoteReward: TypedContractMethod<[addr: AddressLike], [bigint], "view">;

  getVoter: TypedContractMethod<
    [addr: AddressLike, eId: BigNumberish],
    [[bigint, boolean, bigint, bigint, bigint]],
    "view"
  >;

  initialize: TypedContractMethod<[], [void], "nonpayable">;

  isAdmin: TypedContractMethod<[account: AddressLike], [boolean], "view">;

  isElector: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  isWithdrawal: TypedContractMethod<[arg0: BigNumberish], [boolean], "view">;

  nodeTox: TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  receiceTime: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  receiveElectReward: TypedContractMethod<[], [void], "nonpayable">;

  receiveVoteReward: TypedContractMethod<[], [void], "nonpayable">;

  removeAdmin: TypedContractMethod<
    [account: AddressLike],
    [void],
    "nonpayable"
  >;

  renounceAdmin: TypedContractMethod<[], [void], "nonpayable">;

  returnNodeToken: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  returnVote: TypedContractMethod<[eId: BigNumberish], [void], "nonpayable">;

  returnVoteToken: TypedContractMethod<
    [eId: BigNumberish],
    [void],
    "nonpayable"
  >;

  rewards: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  setAboutAddress: TypedContractMethod<
    [_globalRewardArrd: AddressLike],
    [void],
    "nonpayable"
  >;

  setElectDuration: TypedContractMethod<
    [duration: BigNumberish],
    [void],
    "nonpayable"
  >;

  setSystemStatus: TypedContractMethod<
    [addr: AddressLike, eID: BigNumberish, status: BigNumberish],
    [void],
    "nonpayable"
  >;

  setVoteDuration: TypedContractMethod<
    [duration: BigNumberish],
    [void],
    "nonpayable"
  >;

  signerAddress: TypedContractMethod<[], [string], "view">;

  systemStatus: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  systemTox: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  totalElectEndTime: TypedContractMethod<
    [arg0: BigNumberish],
    [bigint],
    "view"
  >;

  totalVoteTox: TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  updateSystemElectorTox: TypedContractMethod<
    [addr: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  vote: TypedContractMethod<
    [eId: BigNumberish, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  voteDuration: TypedContractMethod<[], [bigint], "view">;

  voteEndTime: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  voteList: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  voteStartTime: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  voteTotalCount: TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  voteTox: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  voted: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [boolean],
    "view"
  >;

  voter: TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [string],
    "view"
  >;

  voterId: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  withdrawalDuration: TypedContractMethod<[], [bigint], "view">;

  withdrawalNode: TypedContractMethod<[], [void], "nonpayable">;

  withdrawalNodeToken: TypedContractMethod<[], [void], "nonpayable">;

  withdrawalTime: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  withdrawalToken: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addAdmin"
  ): TypedContractMethod<[account: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "allAdmins"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "batchAddAdmin"
  ): TypedContractMethod<[amounts: AddressLike[]], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "electDuration"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "electEndTime"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "electNode"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "electRewards"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "electStartTime"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "electStatus"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "electTox"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "elector"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "electorId"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "endElectorId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "erc20Address"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getElectReward"
  ): TypedContractMethod<[addr: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getElector"
  ): TypedContractMethod<
    [eId: BigNumberish],
    [[string, bigint, bigint, boolean, bigint]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getElectorStatus"
  ): TypedContractMethod<[eId: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "getEndElectorId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getVoteList"
  ): TypedContractMethod<[addr: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getVoteListLength"
  ): TypedContractMethod<[addr: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getVoteReward"
  ): TypedContractMethod<[addr: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getVoter"
  ): TypedContractMethod<
    [addr: AddressLike, eId: BigNumberish],
    [[bigint, boolean, bigint, bigint, bigint]],
    "view"
  >;
  getFunction(
    nameOrSignature: "initialize"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "isAdmin"
  ): TypedContractMethod<[account: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isElector"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isWithdrawal"
  ): TypedContractMethod<[arg0: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "nodeTox"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "receiceTime"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "receiveElectReward"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "receiveVoteReward"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "removeAdmin"
  ): TypedContractMethod<[account: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "renounceAdmin"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "returnNodeToken"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "returnVote"
  ): TypedContractMethod<[eId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "returnVoteToken"
  ): TypedContractMethod<[eId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "rewards"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "setAboutAddress"
  ): TypedContractMethod<
    [_globalRewardArrd: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setElectDuration"
  ): TypedContractMethod<[duration: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setSystemStatus"
  ): TypedContractMethod<
    [addr: AddressLike, eID: BigNumberish, status: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setVoteDuration"
  ): TypedContractMethod<[duration: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "signerAddress"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "systemStatus"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "systemTox"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "totalElectEndTime"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalVoteTox"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "updateSystemElectorTox"
  ): TypedContractMethod<
    [addr: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "vote"
  ): TypedContractMethod<
    [eId: BigNumberish, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "voteDuration"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "voteEndTime"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "voteList"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "voteStartTime"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "voteTotalCount"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "voteTox"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "voted"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "voter"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "voterId"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "withdrawalDuration"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "withdrawalNode"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdrawalNodeToken"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdrawalTime"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "withdrawalToken"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  getEvent(
    key: "AdminAdded"
  ): TypedContractEvent<
    AdminAddedEvent.InputTuple,
    AdminAddedEvent.OutputTuple,
    AdminAddedEvent.OutputObject
  >;
  getEvent(
    key: "AdminRemoved"
  ): TypedContractEvent<
    AdminRemovedEvent.InputTuple,
    AdminRemovedEvent.OutputTuple,
    AdminRemovedEvent.OutputObject
  >;
  getEvent(
    key: "ElectorDetail"
  ): TypedContractEvent<
    ElectorDetailEvent.InputTuple,
    ElectorDetailEvent.OutputTuple,
    ElectorDetailEvent.OutputObject
  >;
  getEvent(
    key: "ElectorWithdrawalToken"
  ): TypedContractEvent<
    ElectorWithdrawalTokenEvent.InputTuple,
    ElectorWithdrawalTokenEvent.OutputTuple,
    ElectorWithdrawalTokenEvent.OutputObject
  >;
  getEvent(
    key: "Initialized"
  ): TypedContractEvent<
    InitializedEvent.InputTuple,
    InitializedEvent.OutputTuple,
    InitializedEvent.OutputObject
  >;
  getEvent(
    key: "Rewards"
  ): TypedContractEvent<
    RewardsEvent.InputTuple,
    RewardsEvent.OutputTuple,
    RewardsEvent.OutputObject
  >;
  getEvent(
    key: "VoterDetail"
  ): TypedContractEvent<
    VoterDetailEvent.InputTuple,
    VoterDetailEvent.OutputTuple,
    VoterDetailEvent.OutputObject
  >;
  getEvent(
    key: "VoterWithdrawalToken"
  ): TypedContractEvent<
    VoterWithdrawalTokenEvent.InputTuple,
    VoterWithdrawalTokenEvent.OutputTuple,
    VoterWithdrawalTokenEvent.OutputObject
  >;

  filters: {
    "AdminAdded(address)": TypedContractEvent<
      AdminAddedEvent.InputTuple,
      AdminAddedEvent.OutputTuple,
      AdminAddedEvent.OutputObject
    >;
    AdminAdded: TypedContractEvent<
      AdminAddedEvent.InputTuple,
      AdminAddedEvent.OutputTuple,
      AdminAddedEvent.OutputObject
    >;

    "AdminRemoved(address)": TypedContractEvent<
      AdminRemovedEvent.InputTuple,
      AdminRemovedEvent.OutputTuple,
      AdminRemovedEvent.OutputObject
    >;
    AdminRemoved: TypedContractEvent<
      AdminRemovedEvent.InputTuple,
      AdminRemovedEvent.OutputTuple,
      AdminRemovedEvent.OutputObject
    >;

    "ElectorDetail(address,uint256,uint256,bool)": TypedContractEvent<
      ElectorDetailEvent.InputTuple,
      ElectorDetailEvent.OutputTuple,
      ElectorDetailEvent.OutputObject
    >;
    ElectorDetail: TypedContractEvent<
      ElectorDetailEvent.InputTuple,
      ElectorDetailEvent.OutputTuple,
      ElectorDetailEvent.OutputObject
    >;

    "ElectorWithdrawalToken(address,uint256)": TypedContractEvent<
      ElectorWithdrawalTokenEvent.InputTuple,
      ElectorWithdrawalTokenEvent.OutputTuple,
      ElectorWithdrawalTokenEvent.OutputObject
    >;
    ElectorWithdrawalToken: TypedContractEvent<
      ElectorWithdrawalTokenEvent.InputTuple,
      ElectorWithdrawalTokenEvent.OutputTuple,
      ElectorWithdrawalTokenEvent.OutputObject
    >;

    "Initialized(uint8)": TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;
    Initialized: TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;

    "Rewards(address,uint256,uint256)": TypedContractEvent<
      RewardsEvent.InputTuple,
      RewardsEvent.OutputTuple,
      RewardsEvent.OutputObject
    >;
    Rewards: TypedContractEvent<
      RewardsEvent.InputTuple,
      RewardsEvent.OutputTuple,
      RewardsEvent.OutputObject
    >;

    "VoterDetail(address,uint256,uint256,bool)": TypedContractEvent<
      VoterDetailEvent.InputTuple,
      VoterDetailEvent.OutputTuple,
      VoterDetailEvent.OutputObject
    >;
    VoterDetail: TypedContractEvent<
      VoterDetailEvent.InputTuple,
      VoterDetailEvent.OutputTuple,
      VoterDetailEvent.OutputObject
    >;

    "VoterWithdrawalToken(address,uint256)": TypedContractEvent<
      VoterWithdrawalTokenEvent.InputTuple,
      VoterWithdrawalTokenEvent.OutputTuple,
      VoterWithdrawalTokenEvent.OutputObject
    >;
    VoterWithdrawalToken: TypedContractEvent<
      VoterWithdrawalTokenEvent.InputTuple,
      VoterWithdrawalTokenEvent.OutputTuple,
      VoterWithdrawalTokenEvent.OutputObject
    >;
  };
}
